server {
    listen 80;

    location / {
        proxy_pass http://shell:80;
    }

    location /auth/ {
        proxy_pass http://auth-mfe:80;
    }

    location /theme/ {
        proxy_pass http://theme-mfe:80;
    }
}