name: Build Frontends

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - shell
          - auth-mfe
          - theme-mfe

    defaults:
      run:
        working-directory: apps/frontend/${{ matrix.app }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: apps/frontend/${{ matrix.app }}/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Build Docker Image
        run: |
          docker build \
            -f Dockerfile.prod \
            -t ${{ matrix.app }}:latest .

